### ISSUE TITLE
How to get line plot of metric expression?

### ISSUE THREAD

**Issue by maria-t** [jan-dolejsi/vscode-pddl#111]
I am trying to solve a problem with popf. And I can't get the line plot of a metric expression. Am I missing something?

**Comment by jan-dolejsi** [comment]
Not necessarily. I have seen many cases, where VAL produces an error instead of the line plot. Must frequent error is a sensation fault.

The way to find out more includes two steps:
1. Open the settings and search for "val verbose". Flip the seeing to true.
2. Open the developer tools through the command pallet. Open the Console pane. Look for the `valueseq` command. Try to execute the same command in the terminal window. See what store y you get.
