### ISSUE TITLE
Plan stuck on "Discovering packages" when using docker-based planutils as backend

### ISSUE THREAD

**Issue by cedricgoubard** [jan-dolejsi/vscode-pddl#142]
Hello,

I'm trying to use the extension on a Mac with the M1 chip. I am using Docker to run a planutils server, and the extension as a client.

I've followed the documentation to set up the docker server (with [a minor change to the Dockerfile](https://github.com/cedricgoubard/planutils/blob/main/Dockerfile), I'm downloading LAMA and flask as part of the image).

 I've configured the planner using the default configuration:
<img width="604" alt="Screenshot 2023-02-07 at 18 00 34" src="https://user-images.githubusercontent.com/40461909/217328846-8ae49be8-bba7-4214-9c19-8842ce1b36c2.png">

But when I press `ALT+P`, it seems to get stuck on  "Discovering packages"
<img width="1055" alt="Screenshot 2023-02-07 at 17 59 59" src="https://user-images.githubusercontent.com/40461909/217328072-ccaaf4f1-9a5c-413a-acb5-211df05d55b5.png">

Running the server gives me the standard Flask output:
```bash
docker run -it --rm --privileged -p 5555:5555 planutils:latest planutils server --port 5555
 * Serving Flask app 'planutils.server'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5555
Press CTRL+C to quit
```

I've had problems with a very slow internet connection inside a container in the past; could it be causing the problem here? If so, is there a way to use the server fully offline?

Any help would be appreciated, and thank you for this very useful extension 👍

**Comment by haz** [comment]
It shouldn't be any slow-down, and running the docker locally is indeed offline already. Can you confirm which configuration you used? I.e., was it localhost or "Planning as a service"?

If the latter, then that's the remote server still in beta. If the former, then is there any chance you're on an arm architecture?

**Comment by cedricgoubard** [comment]
I used the `http://localhost:5555/package`, but I am indeed on an arm architecture (Mac with the M1 chip). 
Do I need to change anything? Looking at the Dockerfile, I don't see anything specific to amd, and the Docker image seems to have built without any problem.

**Comment by haz** [comment]
I think we're kinda outa luck here. Some related issues and discussion...

- https://github.com/AI-Planning/planutils/issues/97
- https://github.com/AI-Planning/planutils/issues/93

The hope was that building the docker image would let us simulate amd binaries on the arm architecture, but it's decidedly not the case. Each individual packge (the there are [[many](https://github.com/AI-Planning/planutils/tree/main/planutils/packages)] would need an arm-compatible build.

It's not really a step back -- since all these planners and planner tech never really worked well with Mac's -- but it's not the step forward we'd hoped. If you can run the server on a linux box locally, that may do the trick. It's the solution I've had to resort to for the planning course I'm teaching.

Sorry to not have better news!

**Comment by cedricgoubard** [comment]
Interesting; I guess that since Singularity is not available on Mac, the only way forward with this would be to build the planners directly inside the `planutils` Docker image (without the intermediate Singularity/Apptainer layer), which might not be possible if the dependencies conflict...

Anyway, thank you for answering the issue, I'll close it since we found a workaround 👍
