### ISSUE TITLE
Securing communication to planning.domains

### ISSUE THREAD

**Issue by haz** [jan-dolejsi/vscode-pddl#163]
Any chance you can swap over the `http://*.planning.domains` URLs to use `https`? We should be good to go on the api, solver, and editor fronts. Some relevant searches...

- https://github.com/search?q=repo%3Ajan-dolejsi%2Fvscode-pddl+http%3A%2F%2F&type=code
- https://github.com/search?q=repo%3Ajan-dolejsi%2Fvscode-pddl+editor.planning&type=code

**Comment by nirlipo** [comment]
I used it recently and instructed my students in the course to switch manually as follows in the meantime:
![image](https://github.com/jan-dolejsi/vscode-pddl/assets/861782/ff775bf9-564c-40c4-a55c-486eb6631c8a)
![image](https://github.com/jan-dolejsi/vscode-pddl/assets/861782/a806de5f-aaba-4b07-a4f1-b3193fffecca)
![image](https://github.com/jan-dolejsi/vscode-pddl/assets/861782/95cfe44c-146e-46db-850d-98bf2efbc9d8)

> 
> Make sure to select the https option once you save the settings. You can select it by using the correct option shown in screenshot1.
> 
> You can use the planning as a service option (like the online option in the https://tinyurl.com/comp90054-pddl that allows the use of multiple online planners)
> 
> For that you can change the URL 45.113... for https://paas-uom.org:5001/package

I had to get a domain for the paas plugin to work with https. @jan-dolejsi , you may use that one instead of the IP.

**Comment by jan-dolejsi** [comment]
Catching up. Sorry for the delay. 

Replacing the `http://*.planning.domains` URLs with `https`, it seems that the `solver` and `editor` are good, but `education` is not using the https yet, right?

**Comment by haz** [comment]
That's correct, but you don't hot-link there, do you? Heroku has been absolutely infuriating to work with (won't take a pre-paid lump sum, so funding of planning.domains is perched precariously now). I may migrate to DigitalOcean in protest, so there may be some devops headaches in our nearterm future. Can likely get the https working for `education`, but we shall see.

**Comment by jan-dolejsi** [comment]
I had one hyperlink to _education_ in the markdown documentation, or somewhere. Ok, will keep that as is for now.

**Comment by jan-dolejsi** [comment]
Updated extension released. Thanks for your patience.
