### ISSUE TITLE
It could not  run,and there are some problems!

### ISSUE THREAD

**Issue by topbobo** [jan-dolejsi/vscode-pddl#23]
**1、**`ctrl +shift + p`

**2、choose** `PDDL:Configue parser`

**3、Then input**`java -javaagent:d:/pddl4j/build/libs/pddl4j-3.8.3.jar -server -Xms2048m -Xmx2048m fr.uga.pddl4j.parser.Parser`
**4、Enter**  
**5、choose this machine**
**6、Then Input**`$(parser) -o $(domain) -f $(problem)`
**7、Enter**

**But it can not run，the problem is ：**
`Command failed: "java -javaagent:d:/pddl4j/build/libs/pddl4j-3.8.3.jar -server -Xms2048m -Xmx2048m fr.uga.pddl4j.parser.Parser" -o C:\Users\ADMINI~1\AppData\Local\Temp\domain-14420qMBYloxqxZBi.pddl -f C:\Users\ADMINI~1\AppData\Local\Temp\problem-14420ZjjdU2b6pZrN.pddl `

**We can see it auto-add "" between my code** 

`"java -javaagent:d:/pddl4j/build/libs/pddl4j-3.8.3.jar -server -Xms2048m -Xmx2048m fr.uga.pddl4j.parser.Parser"`

### **What should I  do with this problem ？** **Help~**

**Comment by jan-dolejsi** [comment]
Thanks for the report. Path with spaces were being automatically enclosed with double quotes unless those were `java -jar` or `node ...` paths. I added `java -javaagent:` to the exceptions. All of this is of course to ease the usage on Windows : (

This will be fixed in the version 2.10.1 that is coming out shortly. Let me know if you find another issue.

**Comment by topbobo** [comment]
**Get it! 
Thanks a lot!!**

**Comment by topbobo** [comment]
**I must say: you are so cool**
