### ISSUE TITLE
':DURATIVE-ACTION' : domain definition expected error and MAX_ARITY problem

### ISSUE THREAD

**Issue by Jieul** [jan-dolejsi/vscode-pddl#41]
Hi, Thank you for creating this extension.
But I have some problems. I'm using vscode with PDDL extension and http://editor.planning.domains. My issues are occuring in both.

First issue is syntax error  when I  declare [:durative-action] in (:requirements) of domain PDDL
error -> 
/tmp/solver_planning_domains_tmp_4TzsVr38bWosI/domain.pddl: syntax error in line 2, ':DURATIVE-ACTION':
domain definition expected

Second issue is MAX_ARITY. I want to use 7 variables (prt-insrt3 ?prt - part ?hol1 ?hol2 ?hol3 - hole ?fsr1 ?fsr2 ?fsr3 - fastener) in :predicates of domain PDDL. But current ARITY is 5 so I can't using that. How can I increase MAX_ARITY?
error -> arity of PRT-INSRT3 to high! increase MAX_ARITY (currently 5)

I have no idea how to solve this problem. Please help.
Thanks!

**Comment by jan-dolejsi** [comment]
Hi! The errors you see are reported by the planning engine that you are invoking. The default configuration points to the solver.planning.domains service. The engine currently hosted there does NOT support durative actions. Unfortunately. This will change in the future. Meanwhile, can you get one of the other well known planners work in your environment?

https://planning.wiki/ref/planners

As this issue is not related to the VS Code extension for PDDL itself, I will close it, if you do not mind. You could get some help with planning at [Stackoverflow](https://stackoverflow.com/questions/tagged/pddl) or [Slack](https://planning.wiki/slack).
